name: Link Check

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: '--cache --max-cache-age 1d --verbose --no-progress .'
          fail: true
          jobSummary: true

      - name: Create Issue From File
        if: failure() && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Broken Links Detected'
          content-filepath: ./lychee/out.md
          labels: |
            automated
            broken-links
